// react-project/src/views/Catalogue.js
import { useState, useEffect } from "react";
import './App.css';
import Navbar from '../component/Navbar.js';
import axios from 'axios';

import { Card, CardActionArea, Typography, CardContent, Button, CardActions } from "@mui/material";
import { useLocation } from "react-router-dom";
import Icon from '@mdi/react';
import { mdiCartArrowDown } from '@mdi/js';


function Catalogue() {

    const { search } = useLocation();
    const params = new URLSearchParams(search);
    const username = params.get('username');
    console.log(username);
    const [products, setProducts] = useState([]);
    const [panier, setPanier] = useState([])

    const addToCart = async ({product}) => {
        try {
            const userId = localStorage.getItem('userId');
            if (!userId) {
              console.error('ID utilisateur non trouvé dans le stockage local');
              return;
            }
        
            await axios.post('http://localhost:3000/api/Addpanier', { user_id: userId, product_id: product.id });
            alert('Produit ajouté au panier avec succès');
          } catch (error) {
            console.error('Erreur lors de l\'ajout du produit au panier:', error);
          }
        setPanier([...panier, product])
        console.log(panier)
    }

    useEffect(() => {
        const fetchProducts = async () => {
            try {
                const response = await axios.post('http://localhost:3000/api/products');
                setProducts(response.data);
            } catch (error) {
                console.error('Erreur lors de la récupération des produits:', error);
            }

        };

        fetchProducts();
    }, []);

    useEffect(() => {

    }, [panier])


    return (
        <>
            {username == null ?
                <Navbar />
                :
                <Navbar
                    username_prop={username}/>}

            {products ?
                <div className="products-container">
                    {products.map((product, index) => (
                        <Card className="shadow hover:shadow-xl" variant="outlined" key={index}>
                            <CardActionArea>
                                <CardContent href=''>
                                    <Typography>{product.id}</Typography>
                                    <Typography>{product.nom}</Typography>
                                    <Typography>{product.categorie}</Typography>
                                    <Typography>{product.prix} €</Typography>
                                </CardContent>
                            </CardActionArea>
                            <CardActions>
                                <Button onClick={() => addToCart({ product })} size="small">Ajouter au panier<Icon path={mdiCartArrowDown} size={1} /></Button>
                            </CardActions>
                            
                        </Card>
                    ))}
                </div>
                : 'Loading...'}
        </>
    );
}

export default Catalogue;

// angular-project/src/app/catalogue/catalogue.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import {MatCardModule} from '@angular/material/card';
import {MatButtonModule} from '@angular/material/button';
import { NavbarComponent } from '../navbar/navbar.component';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { AppComponent } from '../app.component';


@Component({
  selector: 'app-catalogue',
  standalone: true,
  imports: [MatCardModule, MatButtonModule, NavbarComponent, CommonModule, HttpClientModule],
  templateUrl: './catalogue.component.html',
  styleUrl: './catalogue.component.css',
})

export class CatalogueComponent implements OnInit {
  username: string | null = null;
  products: any[] = [];
  panier: any[] = [];

  constructor(private route: ActivatedRoute, private http: HttpClient, private app: AppComponent) { }

  ngOnInit(): void {
      this.route.queryParams.subscribe(params => {
        
          this.username = params['username'];
          if(this.username !== null){
            this.app.setUsername(this.username);
          }
      });
      this.app.ngOnInit();
      console.log(this.username)
      this.fetchProducts();
  }

  fetchProducts(): void {
    
      this.http.post<any[]>('http://localhost:3000/api/products', {}).subscribe(
          (response) => {
              this.products = response;
          },
          (error) => {
              console.error('Erreur lors de la récupération des produits:', error);
          }
      );
  }

  addToCart(product: any): void {
      const userId = localStorage.getItem('userId');
      if (!userId) {
          console.error('ID utilisateur non trouvé dans le stockage local');
          return;
      }
      this.http.post('http://localhost:3000/api/Addpanier', { user_id: userId, product_id: product.id }).subscribe(
          () => {
              alert('Produit ajouté au panier avec succès');
              this.panier.push(product);
          },
          (error) => {
              console.error('Erreur lors de l\'ajout du produit au panier:', error);
          }
      );
  }

}

<div class="products-container">
    <mat-card *ngFor="let product of products" class="shadow hover:shadow-xl">
            <mat-card-content>
                <p>{{ product.id }}</p>
                <p>{{ product.nom }}</p>
                <p>{{ product.categorie }}</p>
                <p>{{ product.prix }} €</p>
            </mat-card-content>
        <mat-card-actions>
            <button mat-button (click)="addToCart(product)" size="small">Ajouter au panier</button>
        </mat-card-actions>
    </mat-card>
</div>
<div *ngIf="!products">Loading...</div>
