// react-project/src/views/Login.js
import { useNavigate } from "react-router-dom";
import Navbar from "../component/Navbar";
import { useState } from "react";
import axios from 'axios';
import { Button, Card, CardContent, TextField, Typography } from "@mui/material";

function Login() {

    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
  
    const navigate = useNavigate();
  
    const handleLogin = async (e) => {
      try {
        const response = await axios.post('http://localhost:3000/api/login', {
          username: username,
          password: password
        });
        const token = response.data.token;
        const id = response.data.id;
        localStorage.setItem('token', token);
        localStorage.setItem('userId', id);
        console.log('Connexion réussie:', response.data);
        // Redirection en utilisant la route qui a pour nom catalogue
        navigate(`/?username=${username}`)
      } catch (error) {
        console.error('Erreur lors de la connexion:', error);
      }
      
  
    };
  
    const toRegister = async (e) => {
      e.preventDefault();
      navigate('/register');
    };
  
    return (
      <div className='background'>
        <Navbar></Navbar>
        <Card className='base-container'>
                <CardContent className='sub-container'>
                    <Typography textAlign={"center"} style={{ fontSize: "4rem"}}>Connexion</Typography>
                    <TextField
                        className="input"
                        type="username"
                        id="username"
                        name="username"
                        placeholder='Pseudo'
                        required={true}
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                    />
                    <TextField
                        className="input"
                        type="password"
                        id="password"
                        name="password"
                        placeholder='Mot de passe'
                        required
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                    />
                    <Button
                        variant="contained"
                        style={{ width: "10rem", alignSelf: "center"}}
                        onClick={handleLogin}>
                        Valider
                    </Button>
                    <Button
                        variant="contained"
                        style={{ width: "10rem", alignSelf: "center"}}
                        onClick={toRegister}>
                        S'inscrire
                    </Button>
                </CardContent>

            </Card>
  
      </div>
    );
}
export default Login;

// vue-project/src/views/Login.vue
<template>
  <div class="login-container">
    <h2>Connexion</h2>
    <form @submit.prevent="login" class="login-form">
      <div class="form-group">
        <input type="email" v-model="email" placeholder="Email" class="form-control">
      </div>
      <div class="form-group">
        <input type="password" v-model="password" placeholder="Mot de passe" class="form-control">
      </div>
      <button type="submit" class="btn btn-primary">Se connecter</button>
    </form>
  </div>
</template>

<script>
import axios from 'axios';
import { useRouter } from 'vue-router';

export default {
  data() {
    return {
      email: '',
      password: ''
    };
  },
  methods: {
    async login() {
      try {
        const response = await axios.post('http://localhost:3000/api/login', {
          username: this.email,
          password: this.password
        });
        const token = response.data.token;
        const id = response.data.id;
        localStorage.setItem('token', token);
        localStorage.setItem('userId', id);
        console.log('Connexion réussie:', response.data);
        // Redirection en utilisant la route qui a pour nom catalogue
        this.$router.push({ name: 'catalogue' }).then(() => {
          // Rafraîchir la page après la redirection
          window.location.reload();
        });
      } catch (error) {
        console.error('Erreur lors de la connexion:', error);
      }
    }
  }
};
</script>

<style scoped>
.login-container {
  max-width: 400px;
  margin: 0 auto;
}

.login-form {
  padding: 20px;
  border-radius: 5px;
}

.form-group {
  margin-bottom: 15px;
}

.form-control {
  width: 100%;
  padding: 10px;
  font-size: 16px;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.btn {
  display: inline-block;
  padding: 10px 20px;
  font-size: 16px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.btn:hover {
  background-color: #0056b3;
}
</style>
