// angular-project/src/app/panier/panier.component.ts
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import {MatListModule} from '@angular/material/list';

@Component({
  selector: 'app-panier',
  standalone: true,
  imports: [CommonModule, MatListModule],
  templateUrl: './panier.component.html',
  styleUrl: './panier.component.css'
})
export class PanierComponent implements OnInit {

  panier: any[] | undefined = undefined;
  totalCost: number = 0;

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.fetchPanier();
  }


  async fetchPanier(): Promise<void> {
    try {
      const userId = localStorage.getItem('userId');
      if (!userId) {
        console.error('ID utilisateur non trouvé dans le stockage local');
        return;
      }
      const response = await this.http.post<any[]>('http://localhost:3000/api/panierUser', { user_id: userId }).toPromise();
      this.panier = response;
      console.log('Produits récupérés:', this.panier);
      this.getTotalPrice();
    } catch (error) {
      console.error('Erreur lors de la récupération des produits:', error);
    }
  }

  async deleteProduct(product: any): Promise<void> {
    try {
      const userId = localStorage.getItem('userId');
      if (!userId) {
        console.error('ID utilisateur non trouvé dans le stockage local');
        return;
      }
      await this.http.post<any[]>('http://localhost:3000/api/subPanier', { user_id: userId, id: product.id }).toPromise();
      console.log('Produit supprimé du panier avec succès');
      await this.fetchPanier();
    } catch (error) {
      console.error('Erreur lors de la suppression du produit au panier:', error);
    }
  }

  getTotalPrice(): void {
    let totalPrice = 0;
    this.panier?.forEach(product => {
      totalPrice += product.Product.prix * product.quantity;
    });
    this.totalCost = Number(totalPrice.toFixed(2));
  }
}

<div class="panier-container">
  <div *ngIf="!panier">
    <p>Ajoutez des produits à votre panier!</p>
  </div>
  <div *ngIf="panier">
    <mat-list *ngFor="let product of panier">
      <div mat-subheader>Votre panier</div>
      <mat-list-item>
        <div>{{ product.quantity }}x {{ product.Product.nom }}</div>
        <button class="delete-button" (click)="deleteProduct(product)">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" /></svg>
        </button>
      </mat-list-item>
    </mat-list>
    <p>Coût total: {{ totalCost }}€</p>
  </div>
</div>

// vue-project/src/views/Panier.vue
<template>
    <div style="position: absolute;
    left:0px;
    top:70px;
    width:100%">
      <h1>Mon panier</h1>
      <h2>Prix total : {{ getTotalPrice() }}</h2>
      <table id="productTable" class="display">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Catégorie</th>
            <th>Quantité</th>
            <th>Prix</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="product in products" :key="product.id">
            <td>{{ product.product_id }}</td>
            <td>{{ product.Product.nom }}</td>
            <td>{{ product.Product.categorie }}</td>
            <td>{{ product.quantity }}</td>
            <td>{{ product.Product.prix * product.quantity }}</td>
            <td><button @click="subToPanier(product.id)">Supprimer Panier</button></td>
          </tr>
        </tbody>
      </table>
    </div>
  </template>

  
  <script>
  import axios from 'axios';
  import $ from 'jquery';
  import 'datatables.net';
  import 'datatables.net-dt/css/dataTables.dataTables.css';
  
  export default {
    name: 'Panier',
    data() {
      return {
        products: []
      };
    },
    async mounted() {
      try {
        const userId = localStorage.getItem('userId');
        const response = await axios.post('http://localhost:3000/api/panierUser', { user_id: userId });
        this.products = response.data;
        console.log('Produits récupérés:', this.products)
      } catch (error) {
        console.error('Erreur lors de la récupération des produits:', error);
      }
      $(document).ready(() => {
  $('#productTable').DataTable({
    lengthChange: false, // Désactiver le choix du nombre d'éléments par page
    paging: false, // Désactiver la pagination
    pageLength: -1 // Afficher le nombre maximal d'éléments par défaut
  });
});

    },
    methods: {
      getTotalPrice() {
      // Initialiser la somme à 0
      let totalPrice = 0;
      // Parcourir chaque produit dans la liste
      this.products.forEach(product => {
        // Ajouter le prix du produit multiplié par la quantité à la somme totale
        totalPrice += product.Product.prix * product.quantity;
      });
      // Retourner la somme totale formatée
      return totalPrice.toFixed(2); // Formatage du nombre pour afficher deux décimales
    },
      async subToPanier(productId) {
    try {
      // Récupérer l'ID de l'utilisateur depuis le stockage local
      const userId = localStorage.getItem('userId');
      if (!userId) {
        console.error('ID utilisateur non trouvé dans le stockage local');
        return;
      }
  
      // Envoyer les données nécessaires au back-end
      await axios.post('http://localhost:3000/api/subPanier', { user_id: userId, id: productId });
      alert('Produit supprimé du panier avec succès');
      window.location.reload();
    } catch (error) {
      console.error('Erreur lors de la suppression du produit au panier:', error);
    }
  }
  
    }
  
  };
  </script>
